 
version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout #alias for git clone\
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run unit tests
          command: |
            NODE_ENV=test && npm run test
 
workflows:
  build_test:
    jobs:
      - run_tests
 